FROM node:22-slim

RUN apt-get update && apt-get install -y curl gnupg2 git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN npm install -g typescript@5.7.2 @angular/cli@19

ARG USER=node
ARG GROUP=node
USER $USER